clear
clc

%import and organize every file within a selcted folder  
datapath=uigetdir([],'Select Data Directory'); 
d=dir(fullfile(datapath,'*.txt'));
for i=1:numel(d)
  txt_file = fullfile(datapath,d(i).name);
    [fid,msg] = fopen(txt_file,'rt');
    assert(fid>=3,msg)
    out = struct();
    while ~feof(fid)
	pos = ftell(fid);
	str = strtrim(fgetl(fid));
	if numel(str)
		spl = regexp(str,':','once','split');
		spl = strtrim(spl);
		if isnan(str2double(spl{1}))
			fnm = strrep(spl{1},' ','');
			val = str2double(spl{2});
			if isnan(val)
				out.(fnm) = spl{2};
			else
				out.(fnm) = val;
			end
		else
			fseek(fid,pos,'bof');
			vec = fscanf(fid,'%*d:%f%f%f%f%f',[1,Inf]);
			out.(fnm) = vec;
            end
    end

    end
    if isequal(out.MSN, 'CF_SetShiftingLightV4') || ...
        isequal(out.MSN, 'CF_SetShiftingSoundV4') || ...
        isequal(out.MSN, 'CF_SetShiftingLightV2') || ...
        isequal(out.MSN, 'CF_SetShiftingSoundV2') || ...
        isequal(out.MSN, 'CF_SetShiftingLightDREADDs') || ...
        isequal(out.MSN,'CF_SetShiftingSoundDREADDs') || ...
        isequal(out.MSN,'CF_SetShiftingLightCIEMICE') || ...
        isequal(out.MSN,'CF_SetShiftingSoundCIEMICE') || ...
        isequal(out.MSN, 'CF-SetShifting07132023') || ...
        isequal(out.MSN, 'CF_SetShifting') || ...
        isequal(out.MSN, 'CF_SetShiftingV6') || ...
        isequal(out.MSN, 'CF_SetShiftingV1-1') || ... 
        isequal(out.MSN, 'CF_SetShiftingSound') || ...
        isequal(out.MSN, 'CF_SetShiftingLight') || ...
        isequal(out.MSN, 'CF_SetShiftLight') || ...
        isequal(out.MSN, 'CF_SetShiftingAfter814') || ...
        isequal(out.MSN, 'CF_SetShifting08172023') || ...
        isequal(out.MSN, 'CF_SetShiftingLight7of9') || ...
        isequal(out.MSN, 'CF_SetShiftingSound7of9') || ...
        isequal(out.MSN, 'CF_1-1New') || ...
        isequal(out.MSN, 'CF_1-1') || ...
        isequal(out.MSN,'1-1A') || ...
        isequal(out.MSN, '1-1B') || ...
        isequal(out.MSN, 'CF_2') || ...
        isequal(out.MSN, 'CF_2-1') || ...
        isequal(out.MSN, 'CF_2-1A') || ...
        isequal(out.MSN, 'CF_2-1New') || ...
        isequal(out.MSN, 'CF_2-1Box7') || ...
        isequal(out.MSN, 'CF_3-1') || ...
        isequal(out.MSN, 'CF_3-2') || ...
        isequal(out.MSN, 'CF_3-3') || ...
        isequal(out.MSN, 'CF_4-1') || ...
        isequal(out.MSN, 'CF_4-2') || ...
        isequal(out.MSN, 'CF_4-3') || ...
        isequal(out.MSN, 'CF_SDLight') || ...
        isequal(out.MSN, 'CF_SDLight2') || ...
        isequal(out.MSN, 'CF_SDLight3') || ...
        isequal(out.MSN, 'CF_SDSound') || ...
        isequal(out.MSN, 'CF_SDSound2') || ...
        isequal(out.MSN, 'CF_SDSound3') || ...
        isequal(out.MSN, 'CF_SD3Light3') || ...
        isequal(out.MSN, 'CF_SD3Light') || ...
        isequal(out.MSN, 'lf_Blink_5_HARDER') || ...
        isequal(out.MSN, 'LF_BLINK_5_HARDER_LEFT')
        Out{i} = out;%variable allOut contains structure of every subject's data
    end
fclose(fid);
% allOut{i} = out;

end

allOut = Out(~cellfun(@isempty, Out)); 
clearvars -except allOut